# Generated by Django 2.2.3 on 2019-07-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
