# Generated by Django 2.2.3 on 2019-07-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190705_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image_url',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg', max_length=250),
        ),
        migrations.AddField(
            model_name='services',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
