# Generated by Django 2.2.3 on 2019-07-05 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190705_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
