# Generated by Django 2.2.3 on 2019-07-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='referral_route',
            field=models.CharField(default='Signpost', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
