# Generated by Django 2.2.3 on 2019-07-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190722_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default='background.jpg', upload_to='testimages'),
        ),
    ]
