# Generated by Django 2.2.3 on 2019-07-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190722_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='background.jpg', upload_to='services/images'),
        ),
    ]
