# Generated by Django 2.2.3 on 2019-07-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20190722_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='no_image.svg', upload_to='service_images'),
        ),
    ]
