# Generated by Django 2.2.3 on 2019-07-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20190722_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='service_images/no_image.svg', upload_to='service_images'),
        ),
    ]
